### ISSUE TITLE
Lost cookie entries except the last one

### ISSUE THREAD

**Issue by kezhuw** [citrusframework/citrus#561] opened 2018-12-01 02:33 UTC
**Citrus Version**
2.7.5

**Expected behavior**
Server gets all cookie entries.

**Actual behavior**
Server gets only last cookie entry.

**Test case sample**

```java
JUnit4CitrusTestDesigner d = new JUnit4CitrusTestDesigner();
d.http().client("clientId")
    .send()
    .delete("/path")
    .cookie(new Cookie("a", "a"))
    .cookie(new Cookie("b", "b"))
```

#543 try to solve this.

**Comment by svettwer** [comment] 2018-12-01 11:09
Hi!

It seems that this issue is at lest linked, if not a duplicate of #455. It could be the case that the root cause is the same but with different symptoms in both issues.

I've extended the test case so that it's executable as a integration test.
```java
public class TodoListIT extends TestNGCitrusTestRunner {

    @Autowired
    private HttpClient httpClient;

    @Autowired
    private HttpServer httpServer;

    @Test
    @CitrusTest
    public void testGet() {

        final Cookie aCookie = new Cookie("a", "a");
        final Cookie bCookie = new Cookie("b", "b");

        http(http -> http.client(httpClient)
                .send()
                .delete("/path")
                .cookie(aCookie)
                .cookie(bCookie));

        http(http -> http.server(httpServer)
                .receive()
                .delete("/path")
                .cookie(aCookie)
                .cookie(bCookie));
    }
}
```

It fails with
```
com.consol.citrus.exceptions.TestCaseFailedException: Validation failed: No matching header for key 'citrus_http_cookie_a'
	at com.consol.citrus.TestCase.executeAction(TestCase.java:227)
	at com.consol.citrus.dsl.runner.DefaultTestRunner.run(DefaultTestRunner.java:188)
	at com.consol.citrus.dsl.runner.DefaultTestRunner.http(DefaultTestRunner.java:540)
	at com.consol.citrus.dsl.testng.TestNGCitrusTestRunner.http(TestNGCitrusTestRunner.java:375)
	at com.consol.citrus.samples.todolist.TodoListIT.testGet(TodoListIT.java:53)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:223)
	at com.consol.citrus.dsl.testng.TestNGCitrusTest.invokeTestMethod(TestNGCitrusTest.java:128)
	at com.consol.citrus.dsl.testng.TestNGCitrusTest.run(TestNGCitrusTest.java:110)
	at com.consol.citrus.dsl.testng.TestNGCitrusTest.run(TestNGCitrusTest.java:56)
	at org.testng.internal.MethodInvocationHelper.invokeHookable(MethodInvocationHelper.java:242)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:579)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
Caused by: com.consol.citrus.exceptions.ValidationException: Validation failed: No matching header for key 'citrus_http_cookie_a'
	at com.consol.citrus.validation.DefaultMessageHeaderValidator.lambda$getHeaderName$4(DefaultMessageHeaderValidator.java:121)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at com.consol.citrus.validation.DefaultMessageHeaderValidator.getHeaderName(DefaultMessageHeaderValidator.java:121)
	at com.consol.citrus.validation.DefaultMessageHeaderValidator.validateMessage(DefaultMessageHeaderValidator.java:60)
	at com.consol.citrus.validation.DefaultMessageHeaderValidator.validateMessage(DefaultMessageHeaderValidator.java:36)
	at com.consol.citrus.validation.AbstractMessageValidator.validateMessage(AbstractMessageValidator.java:46)
	at com.consol.citrus.actions.ReceiveMessageAction.validateMessage(ReceiveMessageAction.java:231)
	at com.consol.citrus.actions.ReceiveMessageAction.doExecute(ReceiveMessageAction.java:128)
	at com.consol.citrus.actions.AbstractTestAction.execute(AbstractTestAction.java:42)
	at com.consol.citrus.dsl.actions.DelegatingTestAction.doExecute(DelegatingTestAction.java:54)
	at com.consol.citrus.actions.AbstractTestAction.execute(AbstractTestAction.java:42)
	at com.consol.citrus.TestCase.executeAction(TestCase.java:220)
	... 32 common frames omitted

```

This matches your report that the *Server gets only last cookie entry.* 

BR,
Sven

**Comment by svettwer** [comment] 2018-12-07 09:19
Changes ported into branch `v2.7-bugfix`

**Closed by svettwer** 2018-12-07 09:19 UTC
Labels: Prio: Medium, TO REVIEW, Type: Bug
