### ISSUE TITLE
Add Java DSL examples in reference guide

### ISSUE THREAD

**Issue by Ernesto-Maserati-CH** [citrusframework/citrus#196] opened 2017-02-01 15:25 UTC
I would drop support for XML test cases. If someone wants XML they can built a Citrus addon for that.

My guess is that there are very few Citrus users who choos XML test scripts.

When I look into the documentation to me it is "polluted" with XML examples, but I am interested into Java examples.

**Comment by christophd** [comment] 2017-02-01 17:28
I doubt that XML is not wanted in the community. Integration testing is very often done by non-developers such as testers that do not have any Java background. This is what we constantly experience from questions and workshops with customers.

However I see your point that some Java DSL examples are missing in the documentation. This is a result from having XML as first and only way of writing tests in Citrus for years.

**Comment by christophd** [comment] 2017-02-01 17:29
I allowed myself to rename the issue to "adding more Java DSL examples to the reference guide"

**Comment by Ernesto-Maserati-CH** [comment] 2017-02-03 12:14
Thank you!

Maybe it would be possible to add language bindings to Citrus framework like Selenium has. I am not sure if that would work for Citrus however, I didn't think this through.

As a programmer I never would choose to write the test script in XML format. People who ae not familiar with programming should not lay their hands on test automation in my opinion.

**Comment by svettwer** [comment] 2019-01-24 13:20
Closed as duplicate of #609 which is on the roadmap for 2019

**Closed by svettwer** 2019-01-24 13:20 UTC
Labels: Prio: Medium, READY, Type: Enhancement
