### ISSUE TITLE
Several Test failures on Windows

### ISSUE THREAD

**Issue by tschlat** [citrusframework/citrus#1038] opened 2023-10-24 14:56 UTC
**Citrus Version**
4.0

**Expected behavior**
When I run the maven build on windows I expect all tests to pass.  I built the framework on windows about two weeks ago. No problem. Today I rebased on master and I have several tests failing. 

**Actual behavior**
Several tests fail.

**Test case sample**
E.g.
[ERROR] Failures: 
[ERROR]   SchemaCollectionParserTest>AbstractBeanDefinitionParserTest.parseBeanDefinitions:43->AbstractBeanDefinitionParserTest.createApplicationContext:57 » BeanCreation
[ERROR]   XsdSchemaRepositoryParserTest>AbstractBeanDefinitionParserTest.parseBeanDefinitions:43->AbstractBeanDefinitionParserTest.createApplicationContext:57 » BeanCreation      
[ERROR]   DomXmlMessageValidatorTest>AbstractTestNGSpringContextTests.run:154->validateSchemaWithSchemaImport:429 » IndexOutOfBounds
[ERROR]   DomXmlMessageValidatorTest>AbstractTestNGSpringContextTests.run:154->validateSchemaWithSchemaImportAndWildcard:451 » IndexOutOfBounds
[ERROR]   DomXmlMessageValidatorTest>AbstractTestNGSpringContextTests.run:154->validateXMLSchemaNested:147 » CitrusRuntime
[ERROR]   DomXmlMessageValidatorTest.validateXMLSchemaNestedError » Test 
The exception ...
[ERROR]   DomXmlMessageValidatorTest>AbstractTestNGSpringContextTests.run:154->validateXMLSchemaNestedWithNamespaceInRoot:176 » CitrusRuntime
[ERROR]   DomXmlMessageValidatorTest.validateXMLSchemaNestedWithNamespaceInRootError » Test
[ERROR]   XsdSchemaRepositoryTest.testResourceLocation:38 expected [1] but found [0]
[ERROR]   XsdSchemaRepositoryTest.testResourceLocationPattern:60 expected [4] but found [0]
[ERROR]   XsdSchemaRepositoryTest.testResourceLocationPatternWithExclusion:83 » CitrusRuntime
[ERROR]   XsdSchemaRepositoryTest.testWsdlResourceLocation:122 expected [1] but found [0]
[ERROR]   WsdlXsdSchemaTest.testWsdlSchemaWsdlImports:73 » CitrusRuntime Failed to load ...
[ERROR]   WsdlXsdSchemaTest.testWsdlSchemaWsdlImportsOnly:100 » CitrusRuntime Failed to ...
[ERROR]   JarWSDLLocatorTest.testGetImportInputSource:38 » IllegalArgument Illegal chara...
[INFO]
[ERROR] Tests run: 397, Failures: 15, Errors: 0, Skipped: 4

**Comment by tschlat** [comment] 2023-10-24 14:57
Any hints where to look? E.g. SchemaCollectionParserTest does not properly load the test context and this has no schemaCollection1 bean.

Can you confirm, that this tests runs properly in your environment?

**Comment by christophd** [comment] 2023-10-24 15:02
probably related to the refactoring of the resource loader implementation

**Comment by tschlat** [comment] 2023-10-24 15:03
could you give me a hint, where this context is actually loaded?^

SchemaCollectionParserTest-context.xml

**Comment by tschlat** [comment] 2023-10-24 15:17
Ok. I just checked this. Seems to be an issue with new new loader implementation.
Stay tuned.

**Comment by christophd** [comment] 2023-10-25 06:57
The problem is in https://github.com/citrusframework/citrus/blob/main/core/citrus-base/src/main/java/org/citrusframework/util/FileUtils.java#L367

The utility uses `File.separator` which resolves to `\` on windows but in this particular scenario we are dealing with classpath resources that should be using "/".

I have fixed it in PR #1039 which got merged already to main branch

@tschlat could you please confirm that tests are fixed on windows with this?

**Comment by bbortt** [comment] 2023-10-25 07:59
hm. throwing in the idea to run a `./mvnw verify` on a [windows image](https://github.com/actions/runner-images#available-images). what do you think?

**Comment by christophd** [comment] 2023-10-25 08:23
@bbortt yep, I was also thinking about this and I think we should do this. For now I thought that the verification by @tschlat may be a shortcut so I can start with the release 😄

**Comment by tschlat** [comment] 2023-10-25 08:33
Yes, I had already fixed that yesterday in my base. That is the first issue which pops up. But there is more. I am currently looking into it.

**Comment by christophd** [comment] 2023-10-25 13:15
Fixed with #1041

**Closed by christophd** 2023-10-25 13:15 UTC
Labels: Type: Bug, Prio: High
